name: Changelog Generator

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
    make:
        runs-on: ubuntu-latest
        steps:
        - name: Automatic Changelog Generator
          # You may pin to the exact commit or the version.
          # uses: CharMixer/auto-changelog-action@72ee445303a13d3fb4ac02a11b5813e70ec3d3d2
          uses: CharMixer/auto-changelog-action@v1.1
          with:
            # Username of the owner of target GitHub repo (default: extracted from $GITHUB_REPOSITORY)
            user: $GITHUB_REPOSITORY
            # Name of project on GitHub (default: extracted from $GITHUB_REPOSITORY)
            project: $GITHUB_REPOSITORY
            release_branch: master
            # Output file. To print to STDOUT instead, use blank as path. (required, default: CHANGELOG.md)
            output: CHANGELOG.md
            # Optional base file to append generated changes to (default: HISTORY.md)
            base: HISTORY.md
            # Changelog will start after specified tag.
            since_tag: relese
            # Changelog will end before specified tag.
            due_tag: new
            # Changelog will exclude specified tags (comma seperated)
            # Issues with the specified labels will be excluded from changelog. Default is "duplicate,question,invalid,wontfix".
            #exclude_labels: # optional
            # Date format. Default is %Y-%m-%d
            date_format: Y-m-d
            # Put the unreleased changes in the specified release number.
            #future_release: # optional

    
